name: Deploy Frontend to Dev

on:
  push:
    branches: [main]
    paths: 
      - 'apps/frontend/**'
      - 'packages/shared/**'
      - 'packages/frontend-deployment/**'
      - '.github/workflows/deploy-frontend-dev.yml'

jobs:
  test-mocked:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run mocked E2E tests
        working-directory: apps/frontend
        run: npm run test:e2e:ci
        
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: test-mocked
    if: success()
    
    # Add permissions for OIDC
    permissions:
      id-token: write # Required to fetch the OIDC token
      contents: read   # Required to checkout the repository
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::560756474135:role/GithubCiInkstreamFrontendDeployRole
          aws-region: eu-west-3
          
      - name: Deploy frontend to dev
        working-directory: packages/frontend-deployment
        run: npm run deploy:dev