name: Frontend E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e-tests:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    env:
      CI: true
      # Increase Node.js memory allocation for better performance
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build:shared

      - name: Copy test environment file
        run: cp apps/frontend/e2e-tests/.env.test apps/frontend/.env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: apps/frontend

      - name: Start dev server in background
        run: |
          cd apps/frontend
          npm run dev &
          npx wait-on http://localhost:5174 --timeout 60000
        env:
          NODE_ENV: development

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: apps/frontend
        env:
          # Additional environment variables for better debugging
          DEBUG: pw:api
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: playwright-report.xml

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/frontend/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: apps/frontend/test-results/
          retention-days: 30